### ISSUE TITLE
Plugin stopped working

### ISSUE THREAD

**Issue by K1N5L4Y3R** [jaunkst/atom-html2haml#16]
It seems like the plugin stopped working yesterday.
I remember that I selected some HTML, ran "Html2haml: Convert" and it worked, but this time the result was _both_ the HTML and the HAML (it didn't delete the HTML). After that, it just won't convert.

It is not giving me an error, as far as I can see. I am not familiar with a procedure to test it to find out the actual issue. Please let me know if/how I can help to investigate this further.

My version of Atom is 1.9.9.

**Comment by jerefrer** [comment]
It seems the webapp used to convert the html is down. See https://github.com/pachkovsky/sublime-html-to-haml/issues/17.

If anyone know who's maintaining the webapp please let us know :pray:

**Comment by jaunkst** [comment]
I am looking into it. Do you think we should make work offline with a gem?

**Comment by K1N5L4Y3R** [comment]
Oops, going through my open issues I found out I never answered. My apologies.
Ever since, I haven't had a problem, so feel free to close this
